### ISSUE TITLE
Wombo API images coming out really broken

### ISSUE THREAD

**Issue by bjshumway** [cdgco/dream-api#4]
My wombo API images are coming out very weird and broken. 

This is what I'm sending for image spec

"input_spec": {
          "style": 5,
          "prompt": 'Merlin',
          "width": 512,
          "height": 512
      }

and its coming out completely busted. Help?

**Comment by bjshumway** [comment]
The image is blurry and doesn't make any sense. Nothing about it looks like Merlin at all.

**Comment by cdgco** [comment]
You might be in the wrong place, my API doesn't take an `input_spec` parameter and is working perfectly fine with the following code:

```
const WomboDream = require('dream-api');

WomboDream.generateImage(5, "Merlin").then((image) => {
    console.log(image);
});
```

**Comment by bjshumway** [comment]
Okay, I am using the same API as this gothub repo... just calling it manually instead of through the github repo.


If you go to the dist folder... and open the dream.js file... you will see that "under the hood" the body that's passed is:

var jsonData = {
        "input_spec": {
            "prompt": prompt,
            "style": style,
            "display_freq": freq
        }
    };


Since I am doing exactly the same thing... how is the quality much better for you?

Can you do me a favor and just check prompt "Merlin" and style 5 ( Fantasy)... and let me know if it returns a good image?

**Comment by bjshumway** [comment]
The only thing I'm doing differently is I am passing a width and a height parameter. I wonder if that could be the cause.... weird.

**Comment by bjshumway** [comment]
Hmmm... still trying to figure this out. When I omit the height and width the task fails.

**Comment by cdgco** [comment]
<img width="1284" alt="Screenshot 2023-02-11 at 8 23 37 PM" src="https://user-images.githubusercontent.com/13807630/218292908-5b0890ae-9361-42df-8081-e84160d80444.png">
You can see in the screenshot, Dream doesn't support height and width parameters, they get disregarded when actually processing the task. From what I can tell, API versions 1 and 2 do not support height and width. The new premium API and wombot do, but they are not publicly available.

Is there a reason why you are trying to use the internal methods instead of the public ones? Are you trying to use a different API endpoint and are you calling the checkStatus function after you generate the task ID? It sounds like the image isn't done processing.
