### ISSUE TITLE
error.response.data

### ISSUE THREAD

**Issue by Nexus52** [cdgco/dream-api#6]
Maybe I'm doing something wrong due to my lack of skills with NodeJS/Javascript but can't get the script working. Getting this response;

C:\Users\XXXXX\node_modules\dream-api\dist\dream.js:147
                resolve(error.response.data);
                                       ^

TypeError: Cannot read properties of undefined (reading 'data')
    at C:\Users\XXXXX\node_modules\dream-api\dist\dream.js:147:40
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by cdgco** [comment]
Have you updated to the latest version? v1.0.9 and earlier no longer work due to deprecation of the old API.

I just ran the test automation and it passed all the tests, so it should be working: https://app.circleci.com/pipelines/github/cdgco/dream-api

If you are on the latest version, are you following the example code from [examples/await.js](https://github.com/cdgco/dream-api/blob/main/examples/await.js) or [examples/promise.js](https://github.com/cdgco/dream-api/blob/main/examples/promise.js)?
