### ISSUE TITLE
API usage restricted?

### ISSUE THREAD

**Issue by darkost12** [cdgco/dream-api#8]
Hello.
`generateImage` returns this regardless of authentication. Also latest test build failed - looks like it's universal restriction
```
{
  detail: 'API abuse is bad for your health. https://www.w.ai/dream-api'
}
```

**Comment by cdgco** [comment]
I think it's odd that they would block authenticated accounts, especially since you can still generate unlimited images from their website without any authentication, but I know they are aware this package, and it seems like they want to kill it. There are many ways to get around their restrictions, but I'm not going to fight them.

The official API is lacking in terms of capabilities and support, and they have absolutely no transparency on limits or pricing which is very disappointing. This package was not meant to compete with their API (it was created months before they ever announced an API) and I was looking forward to the official API, but they don't seem to care about developer support.

Nevertheless, I don't want to completely give up on this package, so I will likely transition this package to support the official API endpoints. 😞

**Comment by cdgco** [comment]
v2.0.0 supporting the official API has been published: https://github.com/cdgco/dream-api/releases/tag/v2.0.0
